<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MicroShader.NavigationEngine</RootNamespace>
    <AssemblyName>MicroShader.NavigationEngine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroShader.Domain\MicroShader.Domain.csproj" />
    <ProjectReference Include="..\MicroShader.ShaderLab\MicroShader.ShaderLab.csproj" />
    <ProjectReference Include="..\MicroShader.IntelliSenseEngine\MicroShader.IntelliSenseEngine.csproj" />
  </ItemGroup>

</Project>
