<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MicroShader.ContextEngine</RootNamespace>
    <AssemblyName>MicroShader.ContextEngine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MicroShader.Domain\MicroShader.Domain.csproj" />
  </ItemGroup>

</Project>
